# set the default docker image
image: registry.gitlab.com/tjvb/phpimages:php74

stages:
  - prepare # prepare the cache
  - check # check the code styles
  - test

prepare_cache:
  stage: prepare
  script:
    - composer validate
    - composer install
  # we use this artifact for all the jobs
  artifacts:
    name: "vendor"
    paths:
      - vendor/*

lint:
  stage: check
  script:
    # lint recursive
    - find src/ -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors detected" )
  dependencies: []

phpcs:
  stage: check
  script:
    - vendor/bin/phpcs
  dependencies:
    - prepare_cache

phpmd:
  image: phpqa/phpmd
  stage: check
  script:
    - phpmd src/ text phpmd.xml.dist
  dependencies: []

test_lowest:
  stage: test
  script:
    # Install composer
    - rm -f composer.lock
    - composer update --prefer-lowest
    - vendor/bin/phpunit --coverage-text --colors=never --log-junit=phpunitresult/junit.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
  dependencies:
    - prepare_cache

test_php74:
  stage: test
  script:
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  dependencies:
    - prepare_cache

test_php80_laravel7:
  stage: test
  image: registry.gitlab.com/tjvb/phpimages:php80
  script:
    - composer  require -w --dev orchestra/testbench=^5.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  dependencies:
    - prepare_cache

test_php80_laravel8:
  stage: test
  image: registry.gitlab.com/tjvb/phpimages:php80
  script:
    - composer  require -w --dev orchestra/testbench=^6.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  dependencies:
    - prepare_cache

test_php80_laravel9:
  stage: test
  image: registry.gitlab.com/tjvb/phpimages:php80
  script:
    - composer require -w --dev orchestra/testbench=^7.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  dependencies:
    - prepare_cache

test_php81_laravel8:
  stage: test
  image: registry.gitlab.com/tjvb/phpimages:php81
  script:
    - composer require -w --dev orchestra/testbench=^6.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  dependencies:
    - prepare_cache

test_php81_laravel9:
  stage: test
  image: registry.gitlab.com/tjvb/phpimages:php81
  script:
    - composer require -w --dev orchestra/testbench=^7.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      cobertura: phpunitresult/cobertura-coverage.xml
  dependencies:
    - prepare_cache
