# set the default docker image
image: registry.gitlab.com/tjvb/phpimages:php74

default:
  interruptible: true

stages:
  - prepare # prepare the cache
  - check # check the code styles
  - test

prepare_cache:
  stage: prepare
  script:
    - composer validate
    - composer install
  # we use this artifact for all the jobs
  artifacts:
    name: "vendor"
    paths:
      - vendor/*

lint:
  stage: check
  script:
    # lint recursive
    - find src/ -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors detected" )
  needs: []
  dependencies: []

phpcs:
  stage: check
  script:
    - vendor/bin/phpcs
  dependencies:
    - prepare_cache

phpmd:
  image: phpqa/phpmd
  stage: check
  script:
    - phpmd src/ text phpmd.xml.dist
  dependencies: []

test_lowest:
  stage: test
  script:
    # Install composer
    - rm -f composer.lock
    - composer update --prefer-lowest
    - vendor/bin/phpunit --coverage-text --colors=never --log-junit=phpunitresult/junit.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache

test:
  stage: test
  parallel:
    matrix:
      - LARAVEL: 7
        TESTBENCH: 5
        PHP:
          - 74
      - LARAVEL: 8
        TESTBENCH: 6
        PHP:
          - 74
          - 80
          - 81
          - 82
      - LARAVEL: 9
        TESTBENCH: 7
        PHP:
          - 80
          - 81
          - 82
  image: registry.gitlab.com/tjvb/phpimages:php$PHP
  script:
    - composer  require -w --dev orchestra/testbench=^$TESTBENCH
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
  needs:
    - prepare_cache
  dependencies:
    - prepare_cache
